export const countryData = [
  { code: "+358", isoCode: "AX", name: "Åland Islands", maxLength: 10 },
  { code: "+93", isoCode: "AF", name: "Afghanistan", maxLength: 9 },
  { code: "+355", isoCode: "AL", name: "Albania", maxLength: 9 },
  { code: "+213", isoCode: "DZ", name: "Algeria", maxLength: 9 },
  { code: "+1684", isoCode: "AS", name: "American Samoa", maxLength: 10 },
  { code: "+376", isoCode: "AD", name: "Andorra", maxLength: 6 },
  { code: "+244", isoCode: "AO", name: "Angola", maxLength: 9 },
  { code: "+1264", isoCode: "AI", name: "Anguilla", maxLength: 10 },
  { code: "+672", isoCode: "AQ", name: "Antarctica", maxLength: 6 },
  { code: "+1268", isoCode: "AG", name: "Antigua and Barbuda", maxLength: 7 },
  { code: "+54", isoCode: "AR", name: "Argentina", maxLength: 10 },
  { code: "+374", isoCode: "AM", name: "Armenia", maxLength: 8 },
  { code: "+297", isoCode: "AW", name: "Aruba", maxLength: 7 },
  { code: "+61", isoCode: "AU", name: "Australia", maxLength: 9 },
  { code: "+43", isoCode: "AT", name: "Austria", maxLength: 10 },
  { code: "+994", isoCode: "AZ", name: "Azerbaijan", maxLength: 9 },
  { code: "+1242", isoCode: "BS", name: "Bahamas", maxLength: 10 },
  { code: "+973", isoCode: "BH", name: "Bahrain", maxLength: 8 },
  { code: "+880", isoCode: "BD", name: "Bangladesh", maxLength: 10 },
  { code: "+1246", isoCode: "BB", name: "Barbados", maxLength: 10 },
  { code: "+375", isoCode: "BY", name: "Belarus", maxLength: 9 },
  { code: "+32", isoCode: "BE", name: "Belgium", maxLength: 9 },
  { code: "+501", isoCode: "BZ", name: "Belize", maxLength: 7 },
  { code: "+229", isoCode: "BJ", name: "Benin", maxLength: 8 },
  { code: "+1441", isoCode: "BM", name: "Bermuda", maxLength: 10 },
  { code: "+975", isoCode: "BT", name: "Bhutan", maxLength: 8 },
  { code: "+591", isoCode: "BO", name: "Bolivia", maxLength: 9 },
  { code: "+387", isoCode: "BA", name: "Bosnia and Herzegovina", maxLength: 8 },
  { code: "+267", isoCode: "BW", name: "Botswana", maxLength: 7 },
  { code: "+55", isoCode: "BR", name: "Brazil", maxLength: 11 },
  {
    code: "+246",
    isoCode: "IO",
    name: "British Indian Ocean Territory",
    maxLength: 7,
  },
  { code: "+673", isoCode: "BN", name: "Brunei", maxLength: 7 },
  { code: "+359", isoCode: "BG", name: "Bulgaria", maxLength: 9 },
  { code: "+226", isoCode: "BF", name: "Burkina Faso", maxLength: 8 },
  { code: "+257", isoCode: "BI", name: "Burundi", maxLength: 8 },
  { code: "+855", isoCode: "KH", name: "Cambodia", maxLength: 9 },
  { code: "+237", isoCode: "CM", name: "Cameroon", maxLength: 9 },
  { code: "+1", isoCode: "CA", name: "Canada", maxLength: 10 },
  { code: "+238", isoCode: "CV", name: "Cape Verde", maxLength: 7 },
  { code: "+345", isoCode: "KY", name: "Cayman Islands", maxLength: 10 },
  {
    code: "+236",
    isoCode: "CF",
    name: "Central African Republic",
    maxLength: 8,
  },
  { code: "+235", isoCode: "TD", name: "Chad", maxLength: 8 },
  { code: "+56", isoCode: "CL", name: "Chile", maxLength: 9 },
  { code: "+86", isoCode: "CN", name: "China", maxLength: 11 },
  { code: "+61", isoCode: "CX", name: "Christmas Island", maxLength: 9 },
  { code: "+61", isoCode: "CC", name: "Cocos (Keeling) Islands", maxLength: 9 },
  { code: "+57", isoCode: "CO", name: "Colombia", maxLength: 10 },
  { code: "+269", isoCode: "KM", name: "Comoros", maxLength: 7 },
  { code: "+242", isoCode: "CG", name: "Congo", maxLength: 9 },
  { code: "+243", isoCode: "CD", name: "DR Congo", maxLength: 9 },
  { code: "+682", isoCode: "CK", name: "Cook Islands", maxLength: 5 },
  { code: "+506", isoCode: "CR", name: "Costa Rica", maxLength: 8 },
  { code: "+225", isoCode: "CI", name: "Côte d'Ivoire", maxLength: 8 },
  { code: "+385", isoCode: "HR", name: "Croatia", maxLength: 9 },
  { code: "+53", isoCode: "CU", name: "Cuba", maxLength: 8 },
  { code: "+599", isoCode: "CW", name: "Curaçao", maxLength: 7 },
  { code: "+357", isoCode: "CY", name: "Cyprus", maxLength: 8 },
  { code: "+420", isoCode: "CZ", name: "Czech Republic", maxLength: 9 },
  { code: "+45", isoCode: "DK", name: "Denmark", maxLength: 8 },
  { code: "+253", isoCode: "DJ", name: "Djibouti", maxLength: 10 },
  { code: "+1767", isoCode: "DM", name: "Dominica", maxLength: 10 },
  { code: "+1849", isoCode: "DO", name: "Dominican Republic", maxLength: 10 },
  { code: "+593", isoCode: "EC", name: "Ecuador", maxLength: 9 },
  { code: "+20", isoCode: "EG", name: "Egypt", maxLength: 10 },
  { code: "+503", isoCode: "SV", name: "El Salvador", maxLength: 8 },
  { code: "+240", isoCode: "GQ", name: "Equatorial Guinea", maxLength: 9 },
  { code: "+291", isoCode: "ER", name: "Eritrea", maxLength: 7 },
  { code: "+372", isoCode: "EE", name: "Estonia", maxLength: 8 },
  { code: "+268", isoCode: "SZ", name: "Eswatini", maxLength: 8 },
  { code: "+251", isoCode: "ET", name: "Ethiopia", maxLength: 9 },
  { code: "+500", isoCode: "FK", name: "Falkland Islands", maxLength: 5 },
  { code: "+298", isoCode: "FO", name: "Faroe Islands", maxLength: 6 },
  { code: "+679", isoCode: "FJ", name: "Fiji", maxLength: 7 },
  { code: "+358", isoCode: "FI", name: "Finland", maxLength: 10 },
  { code: "+33", isoCode: "FR", name: "France", maxLength: 9 },
  { code: "+594", isoCode: "GF", name: "French Guiana", maxLength: 9 },
  { code: "+689", isoCode: "PF", name: "French Polynesia", maxLength: 6 },
  {
    code: "+262",
    isoCode: "TF",
    name: "French Southern Territories",
    maxLength: 6,
  },
  { code: "+241", isoCode: "GA", name: "Gabon", maxLength: 7 },
  { code: "+220", isoCode: "GM", name: "Gambia", maxLength: 7 },
  { code: "+995", isoCode: "GE", name: "Georgia", maxLength: 9 },
  { code: "+49", isoCode: "DE", name: "Germany", maxLength: 11 },
  { code: "+233", isoCode: "GH", name: "Ghana", maxLength: 9 },
  { code: "+350", isoCode: "GI", name: "Gibraltar", maxLength: 8 },
  { code: "+30", isoCode: "GR", name: "Greece", maxLength: 10 },
  { code: "+299", isoCode: "GL", name: "Greenland", maxLength: 6 },
  { code: "+1473", isoCode: "GD", name: "Grenada", maxLength: 10 },
  { code: "+590", isoCode: "GP", name: "Guadeloupe", maxLength: 9 },
  { code: "+1671", isoCode: "GU", name: "Guam", maxLength: 10 },
  { code: "+502", isoCode: "GT", name: "Guatemala", maxLength: 8 },
  { code: "+44", isoCode: "GG", name: "Guernsey", maxLength: 10 },
  { code: "+224", isoCode: "GN", name: "Guinea", maxLength: 9 },
  { code: "+245", isoCode: "GW", name: "Guinea-Bissau", maxLength: 7 },
  { code: "+592", isoCode: "GY", name: "Guyana", maxLength: 7 },
  { code: "+509", isoCode: "HT", name: "Haiti", maxLength: 8 },
  {
    code: "+672",
    isoCode: "HM",
    name: "Heard Island and McDonald Islands",
    maxLength: 6,
  },
  { code: "+39", isoCode: "VA", name: "Vatican City", maxLength: 10 },
  { code: "+504", isoCode: "HN", name: "Honduras", maxLength: 8 },
  { code: "+852", isoCode: "HK", name: "Hong Kong", maxLength: 8 },
  { code: "+36", isoCode: "HU", name: "Hungary", maxLength: 9 },
  { code: "+354", isoCode: "IS", name: "Iceland", maxLength: 7 },
  { code: "+91", isoCode: "IN", name: "India", maxLength: 10 },
  { code: "+62", isoCode: "ID", name: "Indonesia", maxLength: 10 },
  { code: "+98", isoCode: "IR", name: "Iran", maxLength: 10 },
  { code: "+964", isoCode: "IQ", name: "Iraq", maxLength: 10 },
  { code: "+353", isoCode: "IE", name: "Ireland", maxLength: 9 },
  { code: "+44", isoCode: "IM", name: "Isle of Man", maxLength: 10 },
  { code: "+972", isoCode: "IL", name: "Israel", maxLength: 9 },
  { code: "+39", isoCode: "IT", name: "Italy", maxLength: 10 },
  { code: "+1876", isoCode: "JM", name: "Jamaica", maxLength: 10 },
  { code: "+81", isoCode: "JP", name: "Japan", maxLength: 10 },
  { code: "+44", isoCode: "JE", name: "Jersey", maxLength: 10 },
  { code: "+962", isoCode: "JO", name: "Jordan", maxLength: 9 },
  { code: "+7", isoCode: "KZ", name: "Kazakhstan", maxLength: 10 },
  { code: "+254", isoCode: "KE", name: "Kenya", maxLength: 9 },
  { code: "+686", isoCode: "KI", name: "Kiribati", maxLength: 5 },
  { code: "+850", isoCode: "KP", name: "North Korea", maxLength: 10 },
  { code: "+82", isoCode: "KR", name: "South Korea", maxLength: 11 },
  { code: "+965", isoCode: "KW", name: "Kuwait", maxLength: 8 },
  { code: "+996", isoCode: "KG", name: "Kyrgyzstan", maxLength: 9 },
  { code: "+856", isoCode: "LA", name: "Laos", maxLength: 10 },
  { code: "+371", isoCode: "LV", name: "Latvia", maxLength: 8 },
  { code: "+961", isoCode: "LB", name: "Lebanon", maxLength: 8 },
  { code: "+266", isoCode: "LS", name: "Lesotho", maxLength: 8 },
  { code: "+231", isoCode: "LR", name: "Liberia", maxLength: 8 },
  { code: "+218", isoCode: "LY", name: "Libya", maxLength: 9 },
  { code: "+423", isoCode: "LI", name: "Liechtenstein", maxLength: 7 },
  { code: "+370", isoCode: "LT", name: "Lithuania", maxLength: 8 },
  { code: "+352", isoCode: "LU", name: "Luxembourg", maxLength: 9 },
  { code: "+853", isoCode: "MO", name: "Macao", maxLength: 8 },
  { code: "+389", isoCode: "MK", name: "North Macedonia", maxLength: 8 },
  { code: "+261", isoCode: "MG", name: "Madagascar", maxLength: 9 },
  { code: "+265", isoCode: "MW", name: "Malawi", maxLength: 9 },
  { code: "+60", isoCode: "MY", name: "Malaysia", maxLength: 9 },
  { code: "+960", isoCode: "MV", name: "Maldives", maxLength: 7 },
  { code: "+223", isoCode: "ML", name: "Mali", maxLength: 8 },
  { code: "+356", isoCode: "MT", name: "Malta", maxLength: 8 },
  { code: "+692", isoCode: "MH", name: "Marshall Islands", maxLength: 7 },
  { code: "+596", isoCode: "MQ", name: "Martinique", maxLength: 9 },
  { code: "+222", isoCode: "MR", name: "Mauritania", maxLength: 8 },
  { code: "+230", isoCode: "MU", name: "Mauritius", maxLength: 7 },
  { code: "+262", isoCode: "YT", name: "Mayotte", maxLength: 9 },
  { code: "+52", isoCode: "MX", name: "Mexico", maxLength: 10 },
  { code: "+691", isoCode: "FM", name: "Micronesia", maxLength: 7 },
  { code: "+373", isoCode: "MD", name: "Moldova", maxLength: 8 },
  { code: "+377", isoCode: "MC", name: "Monaco", maxLength: 9 },
  { code: "+976", isoCode: "MN", name: "Mongolia", maxLength: 8 },
  { code: "+382", isoCode: "ME", name: "Montenegro", maxLength: 8 },
  { code: "+1664", isoCode: "MS", name: "Montserrat", maxLength: 10 },
  { code: "+212", isoCode: "MA", name: "Morocco", maxLength: 9 },
  { code: "+258", isoCode: "MZ", name: "Mozambique", maxLength: 9 },
  { code: "+95", isoCode: "MM", name: "Myanmar", maxLength: 9 },
  { code: "+264", isoCode: "NA", name: "Namibia", maxLength: 9 },
  { code: "+674", isoCode: "NR", name: "Nauru", maxLength: 7 },
  { code: "+977", isoCode: "NP", name: "Nepal", maxLength: 10 },
  { code: "+31", isoCode: "NL", name: "Netherlands", maxLength: 9 },
  { code: "+687", isoCode: "NC", name: "New Caledonia", maxLength: 6 },
];
