export const skillsData = [
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "Java",
  "C++",
  "HTML",
  "CSS",
  "SQL",
  "AWS",
  "Docker",
  "Git",
  "MongoDB",
  "Express.js",
  "TypeScript",
  "Redux",
  "Bootstrap",
  "Tailwind CSS",
  "Vue.js",
  "GraphQL",
  "Swift",
  "Kotlin",
  "Angular",
  "Sass",
  "jQuery",
  "Flutter",
  "Django",
  "Ruby on Rails",
  "Go",
  "Rust",
  "C#",
  "PHP",
  "Laravel",
  "Android Development",
  "iOS Development",
  "Vuex",
  "NestJS",
  "Next.js",
  "Nuxt.js",
  "Serverless",
  "Firebase",
  "Elasticsearch",
  "Kubernetes",
  "Terraform",
  "GraphQL API",
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "React Native",
  "Electron",
  "Apache Kafka",
  "Apache Spark",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Redis",
  "RabbitMQ",
  "OAuth",
  "JWT",
  "OpenID Connect",
  "Firebase Authentication",
  "WebSockets",
  "GraphQL Client",
  "Prisma",
  "Socket.io",
  "Vim",
  "VSCode",
  "IntelliJ IDEA",
  "PyCharm",
  "Sublime Text",
  "Eclipse",
  "Bitbucket",
  "GitHub",
  "GitLab",
  "CircleCI",
  "Jenkins",
  "Travis CI",
  "AWS Lambda",
  "AWS S3",
  "AWS EC2",
  "Azure",
  "Google Cloud Platform",
  "IBM Cloud",
  "DigitalOcean",
  "Terraform",
  "Ansible",
  "Chef",
  "Puppet",
  "Bash",
  "Zsh",
  "PowerShell",
  "Markdown",
  "LaTeX",
  "WebRTC",
  "OAuth 2.0",
  "SEO",
  "Google Analytics",
  "Firebase Analytics",
  "Stripe",
  "PayPal Integration",
  "Payment Gateway Integration",
  "Agile",
  "Scrum",
  "Kanban",
  "Project Management",
  "Trello",
  "Jira",
  "Confluence",
  "Figma",
  "Adobe XD",
  "Sketch",
  "InVision",
  "UI/UX Design",
  "Wireframing",
  "Prototyping",
  "A/B Testing",
  "Google Tag Manager",
  "Web Design",
  "Responsive Design",
  "Cross-Browser Testing",
  "Unit Testing",
  "Integration Testing",
  "UI Testing",
  "Continuous Integration",
  "Continuous Deployment",
  "DevOps",
  "CI/CD",
  "Agile Development",
  "Mobile App Development",
  "Game Development",
  "AR/VR Development",
  "3D Modeling",
  "Animation",
  "Unity",
  "Unreal Engine",
  "Blender",
  "Solidity",
  "Blockchain",
  "Ethereum",
  "Smart Contracts",
  "Cryptocurrency",
  "Bitcoin",
  "NFTs",
  "IPFS",
  "Web3.js",
  "Truffle Suite",
  "Hardhat",
  "Chainlink",
  "Polkadot",
  "Binance Smart Chain",
  "Cardano",
  "Ripple",
  "Hyperledger",
  "OpenZeppelin",
  "Decentralized Finance (DeFi)",
  "Golang",
  "Julia",
  "Scala",
  "Haskell",
  "Clojure",
  "Lisp",
  "OCaml",
  "Elixir",
  "F#",
  "VHDL",
  "Verilog",
  "MATLAB",
  "R",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Neural Networks",
  "Computer Vision",
  "Natural Language Processing",
  "Data Mining",
  "Data Visualization",
  "Big Data",
  "Apache Hadoop",
  "Apache Storm",
  "Pandas",
  "NumPy",
  "SciPy",
  "Scikit-learn",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "XGBoost",
  "LightGBM",
  "Kaggle",
  "Jupyter Notebooks",
  "Data Wrangling",
  "Data Preprocessing",
  "Model Evaluation",
  "Supervised Learning",
  "Unsupervised Learning",
  "Reinforcement Learning",
  "Clustering",
  "Classification",
  "Regression",
  "Time Series Analysis",
  "Forecasting",
  "Anomaly Detection",
  "Feature Engineering",
  "Hyperparameter Tuning",
  "Cross-Validation",
  "Gradient Descent",
  "SVM",
  "Random Forest",
  "Naive Bayes",
  "Xamarin",
  "SwiftUI",
  "Flutter Development",
  "Android Studio",
  "iOS Swift",
  "CocoaPods",
  "React Hooks",
  "Next.js",
  "Nuxt.js",
  "Gatsby.js",
  "Svelte",
  "Tailwind UI",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "PrimeNG",
  "Bulma",
  "Foundation",
  "Foundation CSS",
  "Pug",
  "EJS",
  "Handlebars",
  "Mustache",
  "Gulp",
  "Grunt",
  "Webpack",
  "Parcel",
  "Vite",
  "Babel",
  "Rollup",
  "ESLint",
  "Prettier",
  "React Testing Library",
  "Cypress",
  "Mocha Testing",
  "Test-Driven Development (TDD)",
  "Jest Testing",
  "Selenium",
  "Postman",
  "Swagger",
  "GraphQL Playground",
  "API Documentation",
  "OAuth 2.0",
  "REST API",
  "SOAP API",
  "WebSocket API",
  "gRPC",
  "PostgreSQL",
  "NoSQL",
  "Firestore",
  "CouchDB",
  "Cassandra",
  "InfluxDB",
  "Apache Cassandra",
  "Elasticsearch",
  "Databases",
  "MongoDB Atlas",
  "Microsoft SQL Server",
  "Oracle Database",
  "SQLite",
  "Firebase Realtime Database",
  "SQLAlchemy",
  "MongoDB Atlas",
  "JDBC",
  "Sequelize",
  "Mongoose",
  "Jupyter",
  "Pytest",
  "Cucumber",
  "Karma",
  "Chai",
  "A/B Testing",
  "Figma Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Adobe After Effects",
  "CorelDRAW",
  "Inkscape",
  "Blender 3D",
  "Cinema 4D",
  "AutoCAD",
  "Revit",
  "SolidWorks",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Amazon Web Services (AWS)",
  "Kubernetes",
  "Docker Swarm",
  "OpenShift",
  "Terraform",
  "Ansible",
  "Jenkins",
  "CI/CD",
  "DevOps",
  "GitLab CI",
  "CircleCI",
  "Puppet",
  "Chef",
  "Vagrant",
  "VirtualBox",
  "VMware",
  "Hyper-V",
  "Linux Administration",
  "Unix",
  "Shell Scripting",
  "Bash",
  "Zsh",
  "Ubuntu",
  "CentOS",
  "Red Hat Linux",
  "Debian",
  "Fedora",
  "Windows Server",
  "Windows PowerShell",
  "CloudFormation",
  "CloudFront",
  "CDN",
  "S3",
  "Lambda",
  "API Gateway",
  "EC2",
  "RDS",
  "Elastic Beanstalk",
  "CloudWatch",
  "CloudTrail",
  "Route 53",
  "VPC",
  "IAM",
  "EKS",
  "Azure DevOps",
  "Google Kubernetes Engine (GKE)",
  "BigQuery",
  "Data Lakes",
  "Apache Kafka",
  "Apache Spark",
  "Apache Flink",
  "Apache Airflow",
  "RabbitMQ",
  "Nginx",
  "HAProxy",
  "Reverse Proxy",
  "Load Balancing",
  "CDN Management",
  "Varnish",
  "Redis",
  "Memcached",
  "Elasticsearch",
  "Grafana",
  "Prometheus",
  "Datadog",
  "New Relic",
  "Nagios",
  "Zabbix",
  "Syslog",
  "Audit Logs",
  "Jira",
  "Confluence",
  "Trello",
  "Slack",
  "Asana",
  "ClickUp",
  "Basecamp",
  "Monday.com",
  "Notion",
  "Airtable",
  "Time Management",
  "Business Analysis",
  "Project Management",
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "Waterfall Methodology",
  "Lean",
  "Six Sigma",
  "Risk Management",
  "Change Management",
  "Stakeholder Management",
  "Budgeting",
  "Forecasting",
  "Performance Management",
  "Operations Management",
  "Product Management",
  "Customer Relationship Management (CRM)",
  "Salesforce",
  "HubSpot",
  "Zoho CRM",
  "Pipedrive",
  "Freshsales",
  "SAP",
  "Oracle ERP",
  "Microsoft Dynamics",
  "ServiceNow",
  "Zendesk",
  "Freshdesk",
  "Helpdesk Support",
  "ITIL",
  "BMC Remedy",
  "SQL Server Management Studio (SSMS)",
  "MySQL Workbench",
  "pgAdmin",
  "MongoDB Compass",
  "DynamoDB",
  "Couchbase",
  "Graph Databases",
  "Neo4j",
  "Cypher",
  "Microsoft Power BI",
  "Tableau",
  "Looker",
  "QlikView",
  "D3.js",
  "PowerShell Scripting",
  "Automation Testing",
  "Selenium WebDriver",
  "JUnit",
  "TestNG",
  "Appium",
  "Robot Framework",
  "Load Testing",
  "JMeter",
  "Gatling",
  "Locust",
  "Continuous Integration",
  "Docker Compose",
  "OpenStack",
  "Terraform Cloud",
  "IBM Watson",
  "OpenAI",
  "ChatGPT",
  "Machine Vision",
  "NLP (Natural Language Processing)",
  "Computer Graphics",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "3D Modelling",
  "Unity3D",
  "Unreal Engine",
  "Game Development",
  "Mobile Game Development",
  "Game Design",
  "Level Design",
  "Game Physics",
  "Motion Graphics",
  "Animation",
  "2D Animation",
  "3D Animation",
  "Rigging",
  "Keyframe Animation",
  "Storyboarding",
  "Film Production",
  "Video Editing",
  "Sound Design",
  "Post-Production",
  "Digital Marketing",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "PPC Advertising",
  "Facebook Ads",
  "Google Ads",
  "Affiliate Marketing",
  "Email Marketing",
  "Content Marketing",
  "Influencer Marketing",
  "Brand Management",
  "Public Relations",
  "Copywriting",
  "Copy Editing",
  "Marketing Automation",
  "Google Analytics",
  "HubSpot Marketing",
  "Hootsuite",
  "Social Media Marketing",
  "YouTube Marketing",
  "Instagram Marketing",
  "Twitter Marketing",
  "LinkedIn Marketing",
  "Pinterest Marketing",
  "TikTok Marketing",
  "Product Launches",
  "E-commerce",
  "Shopify",
  "WooCommerce",
  "Magento",
  "BigCommerce",
  "Shopify Plus",
  "Dropshipping",
  "Amazon FBA",
  "Artificial Intelligence (AI)",
  "Deep Reinforcement Learning",
  "Speech Recognition",
  "Image Processing",
  "Face Recognition",
  "Object Detection",
  "Speech Synthesis",
  "Generative Adversarial Networks (GANs)",
  "AI Ethics",
  "Robotic Process Automation (RPA)",
  "Autonomous Vehicles",
  "Quantum Computing",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "3D Modeling",
  "3D Animation",
  "Computer Graphics",
  "Game Development",
  "Unity 3D",
  "Unreal Engine",
  "Game Design",
  "Mobile Game Development",
  "Blender 3D",
  "AWS Lambda",
  "AWS EC2",
  "AWS S3",
  "AWS DynamoDB",
  "AWS RDS",
  "AWS Elastic Beanstalk",
  "Google Cloud Functions",
  "Google Cloud Compute Engine",
  "Google Cloud Storage",
  "Google Cloud SQL",
  "Azure Functions",
  "Azure App Services",
  "Azure Blob Storage",
  "Azure SQL Database",
  "Docker Compose",
  "Kubernetes",
  "Containerization",
  "Microservices Architecture",
  "Serverless Architecture",
  "CI/CD",
  "Jenkins",
  "GitLab CI",
  "Travis CI",
  "CircleCI",
  "Ansible",
  "Terraform",
  "Chef",
  "Puppet",
  "AWS CloudFormation",
  "Linux Server Administration",
  "Unix",
  "Bash Scripting",
  "Shell Scripting",
  "Nginx",
  "Apache HTTP Server",
  "Tomcat",
  "Web Server Administration",
  "Load Balancing",
  "Reverse Proxy",
  "DNS Management",
  "Vagrant",
  "VirtualBox",
  "Hyper-V",
  "VMware",
  "Microsoft Exchange Server",
  "Cloud Security",
  "Network Security",
  "Ethical Hacking",
  "Penetration Testing",
  "Firewalls",
  "VPN",
  "SSL/TLS",
  "Data Encryption",
  "Risk Assessment",
  "Compliance Management",
  "OWASP Top 10",
  "Security Audits",
  "Two-Factor Authentication (2FA)",
  "Public Key Infrastructure (PKI)",
  "Security Incident Management",
  "Blockchain Development",
  "Solidity Smart Contracts",
  "Ethereum Blockchain",
  "NFT Development",
  "IPFS Storage",
  "Hyperledger Fabric",
  "DApp Development",
  "Bitcoin Development",
  "Cryptographic Algorithms",
  "Smart Contract Audits",
  "Consensus Mechanisms",
  "Decentralized Applications (DApps)",
  "Web3 Development",
  "IPFS",
  "Truffle Suite",
  "Hardhat",
  "Chia Blockchain",
  "Polygon",
  "Avalanche",
  "Binance Coin",
  "Ripple (XRP)",
  "Cardano Blockchain",
  "Solana Blockchain",
  "Tezos",
  "Polkadot Blockchain",
  "Litecoin",
  "Dogecoin",
  "Chainlink",
  "Fantom",
  "Binance Smart Chain (BSC)",
  "Crypto Trading",
  "Cryptocurrency Wallets",
  "Decentralized Finance (DeFi)",
  "Digital Marketing",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "Content Marketing",
  "Social Media Marketing",
  "PPC (Pay-Per-Click)",
  "Google Ads",
  "Facebook Ads",
  "Email Marketing",
  "Marketing Automation",
  "Google Analytics",
  "Facebook Analytics",
  "Google Tag Manager",
  "WordPress Development",
  "Shopify Development",
  "Squarespace Development",
  "Web Design",
  "Wireframing",
  "UI Design",
  "UX Design",
  "User Research",
  "Prototyping",
  "Sketch",
  "Figma Prototyping",
  "Adobe XD",
  "InVision",
  "User Interface Design",
  "Design Systems",
  "Interaction Design",
  "UI/UX Testing",
  "Customer Journey Mapping",
  "Product Management",
  "Agile Methodology",
  "Scrum Framework",
  "Kanban",
  "Lean Startup",
  "Project Management",
  "Task Management",
  "Asana",
  "Trello",
  "Jira",
  "Monday.com",
  "Basecamp",
  "Confluence",
  "Microsoft Project",
  "Team Collaboration",
  "Time Management",
  "Business Analysis",
  "Business Intelligence",
  "Enterprise Resource Planning (ERP)",
  "Customer Relationship Management (CRM)",
  "Salesforce",
  "HubSpot",
  "Zoho CRM",
  "Freshsales",
  "Pipedrive",
  "SAP",
  "Microsoft Dynamics 365",
  "Zoho Analytics",
  "Tableau",
  "Power BI",
  "Google Data Studio",
  "Looker",
  "Qlik Sense",
  "IBM Cognos",
  "Business Intelligence",
  "Data Science",
  "Data Analytics",
  "Data Mining",
  "Predictive Analytics",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Natural Language Processing",
  "Computer Vision",
  "Big Data",
  "Hadoop",
  "Apache Spark",
  "Apache Flume",
  "ETL Processes",
  "Data Warehousing",
  "Data Modeling",
  "Data Visualization",
  "SQL",
  "NoSQL",
  "Data Lakes",
  "Data Governance",
  "Metadata Management",
  "Business Analysis",
  "Product Strategy",
  "Market Research",
  "Digital Transformation",
  "Operations Research",
  "Change Management",
  "Process Automation",
  "Agile Project Management",
  "Lean Six Sigma",
  "Scrum Master",
  "Stakeholder Engagement",
  "Risk Management",
  "Financial Modeling",
  "Cost Analysis",
  "Budgeting & Forecasting",
  "Taxation",
  "Accounting Software",
  "QuickBooks",
  "Xero",
  "Sage",
  "Microsoft Excel",
  "Financial Reporting",
  "Mergers & Acquisitions",
  "Regulatory Compliance",
  "Internal Audits",
  "External Audits",
  "Revenue Recognition",
  "Sales Operations",
  "Sales Forecasting",
  "Business Development",
  "Client Relationship Management",
  "Negotiation",
  "Brand Strategy",
  "Public Relations",
  "Event Planning",
  "Corporate Communications",
  "Media Relations",
  "Crisis Management",
  "Press Releases",
  "SEO Audits",
  "Content Strategy",
  "Content Creation",
  "B2B Marketing",
  "B2C Marketing",
  "Affiliate Marketing",
  "Email Campaigns",
  "Copywriting",
  "Creative Direction",
  "Social Media Advertising",
  "Google Ads Campaigns",
  "Facebook Ads Manager",
  "Instagram Ads",
  "LinkedIn Ads",
  "Video Production",
  "Graphic Design",
  "UX/UI Design",
  "Wireframing",
  "Prototyping",
  "User Research",
  "A/B Testing",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Canva",
  "Brand Identity Design",
  "Logo Design",
  "Illustration",
  "Photography",
  "3D Modelling",
  "VR Design",
  "UX Writing",
  "Interaction Design",
  "Accessibility Design",
  "Game Design",
  "Game Engines",
  "Unity3D",
  "Unreal Engine",
  "Blender",
  "3D Animation",
  "Motion Graphics",
  "After Effects",
  "Premiere Pro",
  "Final Cut Pro",
  "Video Editing",
  "Storyboarding",
  "Post-production",
  "Music Composition",
  "Sound Engineering",
  "Podcasting",
  "Voice Acting",
  "Event Marketing",
  "Brand Activation",
  "Market Segmentation",
  "Customer Insights",
  "Consumer Behavior",
  "Customer Experience",
  "Customer Retention",
  "Lead Generation",
  "CRM Tools",
  "Salesforce CRM",
  "HubSpot CRM",
  "Zoho CRM",
  "SAP CRM",
  "Zendesk",
  "Freshdesk",
  "Zendesk Support",
  "Product Marketing",
  "E-commerce Marketing",
  "Conversion Rate Optimization",
  "User Acquisition",
  "Customer Onboarding",
  "Mobile Marketing",
  "App Store Optimization",
  "Google Analytics",
  "Hotjar",
  "Kissmetrics",
  "Mixpanel",
  "Web Optimization",
  "Sales Training",
  "Cold Calling",
  "Negotiation Skills",
  "Team Leadership",
  "Conflict Resolution",
  "Team Collaboration",
  "Hiring & Recruitment",
  "Interviewing Skills",
  "Talent Acquisition",
  "Employee Engagement",
  "Workplace Wellness",
  "Employee Onboarding",
  "Workforce Planning",
  "HR Management Systems",
  "Learning & Development",
  "Leadership Development",
  "Performance Management",
  "Compensation & Benefits",
  "HR Compliance",
  "Employee Relations",
  "Organizational Development",
  "Legal Research",
  "Legal Writing",
  "Contract Law",
  "Labor Law",
  "Corporate Law",
  "Intellectual Property",
  "Employment Law",
  "Litigation Support",
  "Legal Drafting",
  "Paralegal",
  "Legal Advice",
  "Project Scheduling",
  "Risk Analysis",
  "Project Estimation",
  "Resource Allocation",
  "Procurement",
  "Supply Chain Management",
  "Vendor Management",
  "Logistics",
  "Inventory Management",
  "Warehouse Management",
  "Shipping & Receiving",
  "Business Continuity Planning",
  "Data Security",
  "Cybersecurity",
  "Incident Response",
  "Network Security",
  "Firewall Management",
  "Penetration Testing",
  "Cryptography",
  "Ethical Hacking",
  "Compliance Auditing",
  "GDPR",
  "ISO 27001",
  "PCI DSS",
  "HIPAA Compliance",
  "Two-Factor Authentication",
  "Cloud Security",
  "DevSecOps",
  "Endpoint Security",
  "Threat Intelligence",
  "Risk Management Framework",
  "UI Design",
  "UX Design",
  "Web Design",
  "Interaction Design",
  "Responsive Design",
  "Mobile App Design",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Usability Testing",
  "A/B Testing",
  "Information Architecture",
  "Visual Design",
  "Branding",
  "Typography",
  "Color Theory",
  "Iconography",
  "Illustration",
  "Logo Design",
  "Storyboarding",
  "Sketch",
  "Figma",
  "Adobe XD",
  "InVision",
  "Wireframe.cc",
  "Zeplin",
  "Marvel App",
  "Canva",
  "Affinity Designer",
  "Gravit Designer",
  "CorelDRAW",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "Adobe Premiere Pro",
  "Cinema 4D",
  "Blender",
  "3D Modeling",
  "Motion Graphics",
  "Animation",
  "UI Prototyping",
  "HTML5",
  "CSS3",
  "JavaScript",
  "Front-End Development",
  "Web Development",
  "Bootstrap",
  "Tailwind CSS",
  "Material Design",
  "Design Systems",
  "Responsive Web Design",
  "User-Centered Design",
  "Design Thinking",
  "Human-Computer Interaction",
  "Product Design",
  "Game Design",
  "UX Writing",
  "Microinteractions",
  "Social Media Graphics",
  "Email Design",
  "E-commerce Design",
  "Design for Accessibility",
  "Design for Mobile",
  "Design for Tablet",
  "Design for Web",
  "Cross-Platform Design",
  "Content Strategy",
  "Data Visualization",
  "Infographics",
  "Experience Design",
  "UI Kit Creation",
  "UI Animation",
  "Virtual Reality Design",
  "Augmented Reality Design",
  "Augmented Reality Prototyping",
  "3D Rendering",
  "UI Design Patterns",
  "Visual Storytelling",
  "Game UI Design",
  "App UI Design",
  "Dashboard Design",
  "Landing Page Design",
  "Conversion Optimization",
  "Product Interface Design",
  "User Flow Design",
  "User Journey Mapping",
  "Customer Persona Creation",
  "Customer Experience Design",
  "Wireframe Design",
  "High-Fidelity Prototyping",
  "Low-Fidelity Prototyping",
  "Rapid Prototyping",
  "Collaborative Design",
  "Feedback Incorporation",
  "Sprint Planning",
  "Agile Design Process",
  "Team Collaboration",
  "Design Critique",
  "Design Workshops",
  "Design Presentations",
  "Client Communication",
  "Creative Direction",
  "Brand Strategy",
  "Brand Identity Design",
  "Marketing Design",
  "Product Packaging Design",
  "Print Design",
  "Editorial Design",
  "Magazine Layout Design",
  "Flyer Design",
  "Poster Design",
  "Book Cover Design",
  "Social Media Design",
  "Web Banners",
  "Infographic Design",
  "Photo Manipulation",
  "Retouching",
  "Vector Illustration",
  "3D Animation",
  "2D Animation",
  "UI Testing",
  "Graphic Design Trends",
  "Interactive Prototyping",
  "UI Elements Design",
  "Event Design",
  "Exhibition Design",
  "Interior Design",
  "Urban Design",
  "Product Packaging",
  "Textile Design",
  "Fashion Design",
  "Furniture Design",
  "Product Photography",
  "Video Editing",
  "Storytelling through Design",
  "Digital Collage",
  "GIF Animation",
  "Interactive Elements",
  "Print Production",
  "Digital Media Design",
  "Creative Suite",
  "Multimedia Design",
  "Mobile UI Design",
  "Customer Interface Design",
  "Project Management for Designers",
  "Freelance Design",
  "Photography",
  "Brand Collateral Design",
  "Product Mockups",
  "Design Handoff",
  "Version Control for Designers",
  "Project Collaboration Tools",
  "Time Management for Designers",
  "Presentation Design",
  "E-learning Design",
  "Video Production",
  "Sound Design",
  "Concept Design",
  "Rapid Iteration",
  "Design Sprint",
  "UI Style Guides",
  "Digital Product Design",
  "User Interface Testing",
  "Creative Brief Writing",
  "Multilingual Design",
  "Web Graphics",
  "Design Prototyping Tools",
  "Corporate Identity Design",
  "Design Systems Management",
];
